//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllergyApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AllergyAppDbEntities : DbContext
    {
        public AllergyAppDbEntities()
            : base("name=AllergyAppDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergen> Allergens { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Allergen_Dish> Allergen_Dish { get; set; }
        public virtual DbSet<Allergen_Ingredient> Allergen_Ingredient { get; set; }
        public virtual DbSet<Dish_Relating> Dish_Relating { get; set; }
        public virtual DbSet<Ingredient_Dish> Ingredient_Dish { get; set; }
        public virtual DbSet<Logs_Restaurant> Logs_Restaurant { get; set; }
        public virtual DbSet<Payment_Company> Payment_Company { get; set; }
        public virtual DbSet<Relating> Relatings { get; set; }
        public virtual DbSet<User_Allergen> User_Allergen { get; set; }
        public virtual DbSet<User_Logs> User_Logs { get; set; }
    }
}
